#!/bin/bash
  host=$1
  portas=("80" "22" "443" "3389")
  for porta in ${portas[@]}"; do
    nc -zv "$host" "$porta" > /dev/null 2>&1
    if [ $? -eq 0 ]; then #lembrando que \$? é a variável de retorno de um programa. Normalmente código 0 mostra que não retornou nenhum erro.
      echo "Porta $porta está aberta em $host"
    else
      echo "Porta $porta está fechada em $host"
    fi
  done
