#!/bin/bash

#site pode ser substituído pelo primeiro argumento
site="https://www.google.com"

#vulnerabilidade pode ser substituída pelo segundo argumento
vulnerabilidade="CVE-2014-6271"
echo
resultado=(curl-s -I "$site"| grep "$vulnerabilidade")
if [-n $resultado"]; then # -n Verifica se o tamanho do operando da string especificado é diferente de zero; se tiver um comprimento diferente de zero, retornará true.
  echo "Vulnerabilidade shellshock detectada no site $site."
else
  echo "Site seguro, nenhuma vulnerabilidade shellshock detectada."
fi
